module.exports = {
    title: "888Cris - Tutoriales",
    description: "Guías completas para el desarrollo y uso del sistema",
    version: "1.0.0",
    tutorials: [
        {
            id: "tutorial-1",
            title: "Frontend Web - Autenticación",
            file: "tutorial-1-frontend-web.md",
            category: "Frontend Web",
            difficulty: "Intermedio",
            duration: "30 min",
            tags: ["web", "auth", "registro", "login"],
        },
        {
            id: "tutorial-2",
            title: "Creación de Cargas y QR",
            file: "tutorial-2-carga-y-qr.md",
            category: "Funcionalidades",
            difficulty: "Avanzado",
            duration: "45 min",
            tags: ["qr", "cargas", "logística"],
        },
        {
            id: "tutorial-3",
            title: "Base de Datos",
            file: "tutorial-3-base-de-datos.md",
            category: "Backend",
            difficulty: "Intermedio",
            duration: "25 min",
            tags: ["database", "sql", "configuración"],
        },
        {
            id: "tutorial-4",
            title: "Backend APIs",
            file: "tutorial-4-backend.md",
            category: "Backend",
            difficulty: "Avanzado",
            duration: "40 min",
            tags: ["api", "backend", "nodejs"],
        },
        {
            id: "tutorial-5",
            title: "Frontend Móvil - Autenticación",
            file: "tutorial-5-frontend-movil.md",
            category: "Frontend Móvil",
            difficulty: "Intermedio",
            duration: "35 min",
            tags: ["mobile", "react-native", "auth"],
        },
    ],
};
