CREATE TABLE IF NOT EXISTS articulo_packing_list (
  id_articulo INTEGER PRIMARY KEY AUTOINCREMENT,
  id_carga INTEGER NOT NULL,
  fecha DATE,
  cn TEXT,
  ref_art TEXT,
  descripcion_espanol TEXT,
  descripcion_chino TEXT,
  unidad TEXT,
  precio_unidad REAL,
  precio_total REAL,
  material TEXT,
  unidades_empaque INTEGER,
  marca_producto TEXT,
  serial TEXT,
  medida_largo REAL,
  medida_ancho REAL,
  medida_alto REAL,
  cbm REAL,
  gw REAL,
  imagen_url TEXT,
  imagen_data BLOB,
  imagen_nombre TEXT,
  imagen_tipo TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_carga) REFERENCES carga(id_carga) ON DELETE CASCADE
);